apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-service
  labels:
    app: appointment-scheduling-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointment-scheduling-service
  template:
    metadata:
      labels:
        app: appointment-scheduling-service
    spec:
      containers:
        - name: appointment-scheduling-service
          image: appointments:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  selector:
    app: appointment-scheduling-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
