apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
  labels:
    app: patient-record-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
        - name: patient-record-service
          image: patient-health-record:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb://127.0.0.1:27017/patient-record-db
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
